-- Insert sample testimonials
INSERT INTO testimonials (client_name, company_name, position, testimonial, rating, project_type, is_featured, is_published) VALUES
('Rajesh Kumar', 'Tech Solutions Pvt Ltd', 'IT Manager', 'NAZ Engineering Systems transformed our entire IT infrastructure. Their professional approach and timely delivery exceeded our expectations. The team was knowledgeable and provided excellent support throughout the project.', 5, 'IT Infrastructure', true, true),
('Priya Sharma', 'Green Energy Corp', 'Operations Director', 'The solar energy system installed by NAZ Engineering has significantly reduced our electricity costs. The installation was seamless and the team provided comprehensive training to our staff.', 5, 'Solar Energy', true, true),
('Amit Patel', 'Secure Systems Ltd', 'Security Head', 'Outstanding CCTV and security system implementation. The remote monitoring capabilities and mobile app integration have greatly enhanced our security operations. Highly recommended!', 5, 'Security Systems', true, true),
('Sunita Gupta', 'Manufacturing Hub', 'Plant Manager', 'The power backup solutions provided by NAZ Engineering ensure uninterrupted operations at our facility. Their UPS systems are reliable and the maintenance service is excellent.', 4, 'Power Backup', false, true),
('Vikram Singh', 'Digital Innovations', 'CTO', 'Professional networking solutions that improved our office connectivity significantly. The team understood our requirements perfectly and delivered a robust network infrastructure.', 5, 'Networking', false, true);

-- Insert sample projects
INSERT INTO projects (title, description, client_name, project_type, technologies, duration_months, budget_range, completion_date, is_featured, is_published) VALUES
('Complete IT Infrastructure Overhaul', 'Comprehensive IT infrastructure setup including servers, networking, and security systems for a 200-employee company.', 'Tech Solutions Pvt Ltd', 'IT Infrastructure', ARRAY['Windows Server', 'VMware', 'Cisco Networking', 'Firewall'], 3, '₹10-25 Lakhs', '2024-01-15', true, true),
('Solar Power Plant Installation', '500KW solar power plant installation with grid-tie system and battery backup for manufacturing facility.', 'Green Energy Corp', 'Solar Energy', ARRAY['Solar Panels', 'Inverters', 'Battery Storage', 'Monitoring System'], 4, 'Above ₹25 Lakhs', '2023-12-20', true, true),
('Enterprise Security System', 'Multi-location CCTV surveillance system with access control and biometric integration.', 'Secure Systems Ltd', 'Security Systems', ARRAY['IP Cameras', 'NVR', 'Access Control', 'Biometric Systems'], 2, '₹5-10 Lakhs', '2024-02-28', true, true),
('Data Center Power Backup', 'Redundant UPS system installation with generator backup for critical data center operations.', 'DataTech Services', 'Power Backup', ARRAY['UPS Systems', 'Generators', 'Power Monitoring', 'Automatic Transfer Switch'], 2, '₹10-25 Lakhs', '2023-11-30', false, true),
('Office Network Upgrade', 'Complete network infrastructure upgrade with WiFi 6, managed switches, and network security.', 'Digital Innovations', 'Networking', ARRAY['WiFi 6', 'Managed Switches', 'Network Security', 'VPN'], 1, '₹1-5 Lakhs', '2024-03-10', false, true);
